
# Site settings
title: Rigs of Rods documentation
baseurl: "http://docs.rigsofrods.org"
url: "http://docs.rigsofrods.org"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
